

tracer.property: "I AM THE SPECIAL-ROUTE DEFAULT"
spring.jpa.database: "MYSQL"
spring.datasource.platform: "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/eagle_eye_local?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
spring.datasource.username: "dev"
spring.datasource.password: "{cipher}7307e06ec44eda907c5b8636719231228ed8fa146301f42500f3dfb5b6ecb88f"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
default.comment: "Spring is Powerful, Spring-Boot even more"